PUT http://localhost:3003/api/blogs/61d3601b4afe8df1c3099fc0
Content-Type: application/json; charset=utf-8

{
    "title" : "TestiOtsikko",
    "author": "Mie Vaan",
    "url": "https://duckduckgo.com",
    "likes": 8
}